export type { AppInstance, CreateAppOptions } from "./app";
export { createApp } from "./app";
export {
	applyStyles,
	type ResolvedSpacing,
	type ResolvedStyles,
	resolveShorthands,
	resolveSpacing,
} from "./apply-styles";
export {
	type BasicColor,
	blecsdParseColor,
	type Color,
	type Color256,
	type ColorizeOptions,
	ColorizeOptionsSchema,
	type ColorLevel,
	type ColorSpec,
	ColorSpecSchema,
	type ColorSupport,
	colorize,
	colorToAnsi,
	colorToHex,
	detectColorLevel,
	getColorDepth,
	hexToColor,
	NAMED_COLOR_RGB,
	packColor,
	parseColor,
	type RGBColor,
	stripAnsi,
	unpackColor,
	validatedColorToHex,
	validatedHexToColor,
	validatedPackColor,
	validatedParseColor,
	validatedUnpackColor,
	visibleLength,
} from "./color";
export type { AppConfig } from "./config";
export { AppConfigSchema, createDefaultConfig } from "./config";
export {
	type ChildLayout,
	ChildLayoutSchema,
	calculateFlexLayout,
	calculateLineCrossSize,
	createFlexLines,
	type FlexContainer,
	FlexContainerSchema,
	type FlexItem,
	FlexItemSchema,
	getCrossGap,
	getMainGap,
	isReversedDirection,
	isRowDirection,
	positionItemOnCrossAxis,
	positionLinesOnCrossAxis,
	positionOnMainAxis,
	resolveFlexSizes,
} from "./layout/flex";
export {
	adjustLayoutForSpacing,
	type ContentArea,
	ContentAreaSchema,
	computeMarginBetween,
	getContentArea,
	getCrossAxisMargins,
	getMainAxisMargins,
	getPaddingOffset,
	inflateBaseSize,
	type Margin,
	MarginSchema,
	type Padding,
	PaddingSchema,
	ZERO_MARGIN,
	ZERO_PADDING,
} from "./layout/spacing";
export { render } from "./render";
export {
	type AlignItems,
	AlignItemsSchema,
	type AlignSelf,
	AlignSelfSchema,
	type BorderStyle,
	BorderStyleSchema,
	type Display,
	DisplaySchema,
	type FlexDirection,
	FlexDirectionSchema,
	type FlexWrap,
	FlexWrapSchema,
	type JustifyContent,
	JustifyContentSchema,
	type Overflow,
	OverflowSchema,
	type Position,
	PositionSchema,
	parseStyles,
	type Styles,
	StylesSchema,
	type TextWrap,
	TextWrapSchema,
} from "./styles";
